global using DevExpress.Mvvm;
global using Oleg_LessonDiary.Views;
global using System;
global using System.Windows.Controls;
global using MaterialDesignThemes.Wpf;
global using MaterialDesignColors;
global using Oleg_LessonDiary.Services;
global using Microsoft.Extensions.Configuration;
global using System.IO;